FLEX = AnalizadorSemantico.l
SIN = AnalizadorSemantico.y
SRC = funciones.c list.c 
SEM = AnalizadorSemantico.tab.c lex.yy.c
SEM_H = AnalizadorSemantico.tab.h
OUT = AnalizadorSemantico.exe 

default:
	bison -d $(SIN) &&\
	flex $(FLEX) &&\
	gcc $(SRC) $(SEM) -o $(OUT) &&\
	del $(SEM) $(SEM_H)
	cmd /c .\$(OUT)
	
	@echo Como este mensaje salio del makefile debe ser el mejor tp
all: default